GyulyVGC/sniffnet

src/utility/translations.rs

Review of the french translation from @Charpy

Update French translation

---

Cargo.lock
Cargo.toml
src/enums/byte_multiple.rs
src/enums/message.rs
src/gui/pages/settings.rs
src/structs/notifications.rs

As suggested in the issue #62 , I tasked myself with increasing test coverage and thought I will get started with notifications.

chore: add some unit test on notification

---

src/enums/language.rs
src/gui/components/modal.rs
src/utility/translations.rs

Should be mostly correct. In a few spots (e.g. Deleting Notifications or quitting analysis) the pop-up window is a bit small for the longer German text, so it looks a bit weird.

Add German translations

---

Cargo.lock
Cargo.toml

Faced with the following error on installing the latest release from github:
```
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
Error: GraphicsCreationFailed(GraphicsAdapterNotFound)
```
I checked in the `ìced` project and immediately saw a possible fix for my problem.  As my first ever `rust` effort it seemed worthwhile to try a simple change to add the "glow" feature and amazingly I had just enough room to `cargo build` and can confirm the resulting binary works like a charm for me.
This was to run on an ancient junk laptop so you probably don't want to make this the default, but perhaps and alternate branch or build or at least a note in the docs might help others with the same issue.  Hence I'm leaving this draft in the hope of feedback.  There are separate commits for …

Use glow feature of iced to overcome unsupported graphics

---

src/translations/types/language.rs

'한국인' is a Korean expression that refers to a person living in Korea, and '한국어' is correct.

Correction of awkward Korean expressions

---

src/cli/mod.rs
src/main.rs
src/networking/types/data_info.rs

This adds `--help`/`-h` and `--version`/`-V` CLI arguments, following the defaults used by [clap](https://docs.rs/clap/latest/clap/). When any of these options is found, we exit with status code 0, which indicates success. When an unknown argument is supplied, we exit with the status code 1. Arguments after `--help`/`--version` are ignored, which I think is not a big deal.
If the plan is to support more CLI arguments, it would make sense to switch to a proper argument parser like clap or [lexopt](https://docs.rs/lexopt/).
Closes #264

feat: support --help and --version CLI arguments

---

CHANGELOG.md
src/main.rs

Just a comment for the purpose of the id string. Related to #292 
Another minor thing. I'll point it out here since it's not so important. I noticed that you set 1190x670 as start size, but in another part of the code you maximize on startup. Don't know if it's intended to work that way but, if you need to maximize on start, maybe don't need to specify a start size...

Update Changelog and add a comment for Settings id field

---

Cargo.lock
Cargo.toml

Disable rustls-tls features of reqwest dependency for ppc64 because of ruslts needs ring, which the latest stable version doesn't support this arch.

fix build failure on powerpc64

---

README.md
src/gui/components/radio.rs
src/gui/pages/settings_language_page.rs
src/translations/translations.rs
src/translations/translations_2.rs
src/translations/types/language.rs

Hi there !
This PR about translation gui to Uzbek language. I think it's important for us :)
If u have any question to me feel free

 fix & add some Uzbek words

---

README.md

This PR adds documentation on how to install sniffnet using nix.

Nix Package Documentation

---

src/gui/pages/settings_language_page.rs
src/translations/translations_2.rs

This PR extends the portuguese translation of sniffnet to translations_2.
This extension is based on the Brazilian variation of the portuguese language, which can be understood by any portuguese speaker.

Portuguese Translation Extension - Translations_2

---

CHANGELOG.md
Cargo.lock
src/countries/types/country.rs
src/gui/components/button.rs
src/gui/pages/connection_details_page.rs
src/gui/pages/overview_page.rs
src/gui/types/sniffer.rs
src/networking/manage_packets.rs
src/networking/types/address_port_pair.rs
src/networking/types/app_protocol.rs
src/networking/types/icmp_type.rs
src/networking/types/info_address_port_pair.rs
src/networking/types/mod.rs
src/networking/types/packet_filters_fields.rs
src/networking/types/port_collection.rs
src/networking/types/protocol.rs
src/report/get_report_entries.rs
src/secondary_threads/check_updates.rs
src/secondary_threads/parse_packets.rs
src/translations/translations_3.rs
src/utils/formatted_strings.rs

This PR finally adds support for ICMP.
This is one of the "basic" functionalities that was still missing in Sniffnet.
Now users can:
- filter ICMP traffic
- view ICMP connections in the list of network connection
- examine each ICMP connection to see which types of ICMP messages are exchanged (see the picture below)
Fixes #288

ICMP support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/mod.rs
src/configs/types/config_device.rs
src/configs/types/config_settings.rs
src/configs/types/config_window.rs
src/configs/types/configs.rs
src/gui/app.rs
src/gui/components/modal.rs
src/gui/pages/connection_details_page.rs
src/gui/pages/initial_page.rs
src/gui/pages/inspect_page.rs
src/gui/pages/notifications_page.rs
src/gui/pages/overview_page.rs
src/gui/pages/settings_general_page.rs
src/gui/pages/settings_notifications_page.rs
src/gui/pages/settings_style_page.rs
src/gui/styles/types/style_type.rs
src/gui/types/message.rs
src/gui/types/sniffer.rs
src/main.rs
src/notifications/types/notifications.rs
src/report/get_report_entries.rs
src/secondary_threads/check_updates.rs
src/utils/formatted_strings.rs

Adds support for graceful termination in presence of `SIGINT`, `SIGTERM`, and `SIGHUP`.
Sniffnet needs to save some configurations (settings, window properties, and name of last sniffed device) before closing.
Gracefully terminating the application when the aforementioned signals are received means being able to save such configurations when the user quits Sniffnet in an unconventional way (e.g., by pressing `ctrl` + `C` in terminal, by sending `kill` command, or by closing the terminal that launched the execution).

Graceful termination

---

CHANGELOG.md
src/gui/pages/overview_page.rs
src/gui/types/message.rs
src/gui/types/sniffer.rs
src/networking/types/data_info.rs
src/report/get_report_entries.rs
src/report/types/report_sort_type.rs
src/report/types/search_parameters.rs
src/report/types/sort_type.rs

Until now, network hosts and services in overview page were always sorted by descending value of cumulative transmitted data (bytes or packets).
This was pretty limiting, primarily because the user couldn't easily see the most recent items involved in network traffic exchanges.
This PR implements the possibility to set a sorting strategy for both the network host and service lists.
By default, items are now sorted by most recent timestamp of last data exchange.
With a simple click users can change this behaviour to sort items by ascending/descending value of cumulative transmitted data (bytes or packets).

Sort options for Host & Service columns in overview page

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/chart/manage_chart_data.rs
src/chart/types/traffic_chart.rs
src/gui/pages/connection_details_page.rs
src/gui/pages/inspect_page.rs
src/gui/pages/notifications_page.rs
src/gui/pages/overview_page.rs
src/gui/pages/settings_notifications_page.rs
src/gui/types/runtime_data.rs
src/gui/types/sniffer.rs
src/networking/types/byte_multiple.rs
src/networking/types/info_traffic.rs
src/notifications/notify_and_log.rs
src/notifications/types/notifications.rs
src/report/types/report_col.rs
src/utils/formatted_strings.rs

This PR changes the **interpolation method** used for data points represented in the traffic chart.
Instead of linear interpolation, now a **cosine-like spline** is used.
This results in a smoother and overall better-looking traffic chart (see pictures below).
***
<div align=center>
<h3> Before </h3>
<h3> After </h3>
</div>

Use smoother curves to interpolate traffic chart data points

---

.gitignore
CHANGELOG.md
Cargo.toml
src/configs/types/config_device.rs
src/gui/pages/initial_page.rs
src/gui/pages/settings_general_page.rs
src/gui/pages/settings_notifications_page.rs
src/gui/types/export_pcap.rs
src/gui/types/message.rs
src/gui/types/mod.rs
src/gui/types/sniffer.rs
src/networking/manage_packets.rs
src/networking/types/capture_context.rs
src/networking/types/mod.rs
src/networking/types/my_link_type.rs
src/secondary_threads/parse_packets.rs
src/translations/translations_3.rs
src/utils/formatted_strings.rs
src/utils/types/file_info.rs

This PR finally implements a feature requested for a long time: the **generation of packet capture files (PCAP)**.
The possibility to export such kind of file is a big step forward in making Sniffnet compatible with most of the existing network monitoring tools.
Users can choose whether they want to generate a capture file (disabled by default) and can set a custom path for it.
_Note: the introduction of this feature completely replaces the old textual report._
Fixes #162 and #291.

Export PCAP files

---

CHANGELOG.md
src/chart/types/traffic_chart.rs
src/gui/styles/scrollbar.rs
src/utils/formatted_strings.rs

See #619 for more information. Fixes #619.

Improve time values on the horizontal axis of the chart

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/mod.rs
src/configs/types/configs.rs
src/main.rs

This PR adds a new CLI argument `--adapter [<NAME>]` to allow immediately starting the capture from a network interface given its name.
If a name isn't passed to the `--adapter` flag, the capture will be started from the latest sniffed adapter, or the default adapter in case it's the very first launch of the app. 
The same is done even in case the passed adapter name is invalid or not existing.
Since Sniffnet's CLI arguments are getting more complex, I decided to start using [clap](https://github.com/clap-rs/clap) to parse them.
Fixes #636.

Add CLI argument `--adapter [<NAME>]` to allow immediately starting the capture from a given network interface

---

CHANGELOG.md
src/gui/components/footer.rs
src/gui/pages/inspect_page.rs
src/gui/pages/settings_general_page.rs
src/gui/pages/thumbnail_page.rs
src/gui/sniffer.rs
src/gui/styles/combobox.rs
src/gui/styles/mod.rs
src/mmdb/types/mmdb_reader.rs
src/networking/manage_packets.rs
src/networking/types/host_data_states.rs
src/networking/types/mod.rs
src/notifications/notify_and_log.rs
src/report/get_report_entries.rs
src/secondary_threads/check_updates.rs
src/secondary_threads/parse_packets.rs

This PR implements network host filters autocompletion via a dropdown menu.
This way, it's now possible to preview featured countries, domains, and ASNs while typing in the respective text input in the _Inspect_ page.
https://github.com/user-attachments/assets/e060c70b-2a44-44bc-a2dc-ff7dc62fc68b
Fixes #354.

Network host filters autocompletion via a dropdown menu

---

CHANGELOG.md
resources/countries_flags/4x3/zz-bogon.svg
src/countries/country_utils.rs
src/countries/flags_pictures.rs
src/gui/pages/connection_details_page.rs
src/networking/manage_packets.rs
src/networking/types/bogon.rs
src/networking/types/data_info_host.rs
src/networking/types/ip_collection.rs
src/networking/types/mod.rs
src/translations/mod.rs
src/translations/translations_4.rs

Until today, Sniffnet tagged as 'Unknown location' all IP addresses for which it wasn't possible to determine the origin.
This PR adds support for tagging _bogon_ IPv4 and IPv6 addresses.
> [!NOTE]
> Some IP addresses and IP ranges are reserved for special use, such as for local or private networks, and should not appear on the public internet.
> These reserved ranges, along with other IP ranges that haven't yet been allocated and therefore also shouldn't appear on the public internet are sometimes known as bogons.
***
Sniffnet will now represent with a _lock_ icon that a connection was established with a bogon IP address, and hovering on it will show additional details about such IP.
Fixes #209.

Provide details about unassigned IPs (bogons)

---

CHANGELOG.md
src/gui/pages/inspect_page.rs
src/gui/pages/overview_page.rs
src/report/get_report_entries.rs
src/report/types/report_col.rs

Show data agglomerates in _Inspect_ page table: it's now possible to see the total number of bytes and packets from the connections shown in the table, real-time updated to reflect the filters set by the user.
Fixes #601.

Show data agglomerates in Inspect page table

---

CHANGELOG.md
src/translations/translations_3.rs
src/translations/translations_4.rs
src/translations/types/language.rs

Translation Update - PT

---

src/gui/styles/types/color_remote.rs
src/secondary_threads/parse_packets.rs

Found via `codespell -q 3 -S "*.pdf,*.rtf,./src/translations" -L aas,aci,daa,fo,ser`

fix various typos

---

CHANGELOG.md
resources/themes/sniff_oled.toml
src/gui/styles/custom_themes/mod.rs
src/gui/styles/custom_themes/oled.rs
src/gui/styles/types/custom_palette.rs

Hello everyone,,
I have created a new theme for visually impaired people and at the same time compatible with OLED screens. I hope this will help to improve the usability of the program for visually impaired people (I am visually impaired myself).

Create the new theme sniff_oled.toml

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
src/main.rs

Add icon to window title bar as pointed out in #715.
Fixes #715.

Add icon to window title bar

---

CHANGELOG.md
src/utils/formatted_strings.rs

Show more information when domain name is short

---

CHANGELOG.md
src/notifications/types/notifications.rs

Fix crash when inserting characters longer than one byte in the text input for byte threshold notification setting.
Fixes #744.

Fix crash when inserting characters longer than one byte in the text input for byte threshold notification setting

---

CHANGELOG.md
src/gui/pages/connection_details_page.rs
src/gui/pages/initial_page.rs
src/gui/sniffer.rs
src/networking/manage_packets.rs
src/networking/types/arp_type.rs
src/networking/types/info_address_port_pair.rs
src/networking/types/mod.rs
src/networking/types/packet_filters_fields.rs
src/networking/types/protocol.rs
src/secondary_threads/parse_packets.rs

Hello!
I'm shu-kitamura.
I took on the challenge #680.
ARP is listed in the protocol list in the menu.
ARP is also shown in the Inspect table.
When I click on the ARP row in the Inspect page table, the type of ARP operation is displayed.

Add ARP support

---

CHANGELOG.md
src/gui/sniffer.rs
src/gui/types/export_pcap.rs

Sniffnet has the luck of [being supported by the Next Generation Internet program](https://sniffnet.net/news/ngi-program/).
The program, facilitated by [NLnet](https://nlnet.nl), not only is financially supporting the app development but is also providing additional services.
One of such additional services is the possibility to have an in-depth penetration test by [Radically Open Security](https://www.radicallyopensecurity.com) aimed at finding potential vulnerabilities and improving the security of the project.
This PR fixes a low severity vulnerability (directory traversal) as pointed out in the full report available in #767.
Fixes #767.

Incorporate feedbacks from ROS security audit

---

CHANGELOG.md
src/chart/types/traffic_chart.rs
src/gui/pages/connection_details_page.rs
src/gui/pages/initial_page.rs
src/gui/pages/overview_page.rs
src/gui/pages/settings_general_page.rs
src/gui/pages/settings_notifications_page.rs
src/gui/sniffer.rs
src/main.rs
src/mmdb/types/mmdb_reader.rs
src/networking/manage_packets.rs
src/networking/types/capture_context.rs
src/networking/types/ip_collection.rs
src/networking/types/my_link_type.rs
src/networking/types/packet_filters_fields.rs
src/networking/types/port_collection.rs
src/notifications/notify_and_log.rs
src/notifications/types/notifications.rs
src/notifications/types/sound.rs
src/report/get_report_entries.rs
src/report/types/search_parameters.rs
src/secondary_threads/parse_packets.rs
src/utils/error_logger.rs
src/utils/formatted_strings.rs
src/utils/mod.rs

Properly handle errors when possible, instead of calling `unwrap`/`expect`.
A new trait `ErrorLogger` has been introduced to log errors to `stderr` in production, allowing to get information about the error kind and its location in the code without panicking (in development builds it will also panic, to easily allow spotting errors when coding).

Error handling to reduce the number of possible crash occurrences

---

CHANGELOG.md
resources/themes/sniffnet_rebrand.toml
src/configs/types/config_device.rs
src/configs/types/config_settings.rs
src/configs/types/config_window.rs
src/gui/sniffer.rs
src/gui/styles/container.rs
src/gui/styles/custom_themes/a11y.rs
src/gui/styles/types/style_type.rs

Add new themes optimised for Accessibility, as suggested as part of NLnet's Accessibility Audit.
The new dark theme will also be used as default palette for the application from now on, since it also reflects the colours of Sniffnet icon and official website.
Fixes #786.
See #760 for more info about other Accessibility problems.
<div align=center>
</div>

Add new themes optimised for Accessibility

---

.github/workflows/package.yml
CHANGELOG.md
README.md

For the past 3 years, Sniffnet Windows Installers were provided unsigned due to the fact that code signing certificates are quite expensive.
Today I'm so happy to announce that Sniffnet was declared eligible to receive a free code signing certificate from [SignPath](https://about.signpath.io), which as part of its activity provides  free certificates to open source projects matching some criteria.
Fixes #894.

Update CI/CD to sign the Windows Installer using SignPath

---

.github/workflows/package.yml
CHANGELOG.md
resources/packaging/linux/AppImage/sniffnet.yml

AppImage packaging using pkg2appimage to convert the Debian package into an AppImage as part of the packaging workflow.
As mentioned in #252

Add AppImage Packaging to CI

---

CHANGELOG.md
src/gui/pages/overview_page.rs
src/gui/sniffer.rs
src/networking/manage_packets.rs
src/networking/parse_packets.rs
src/networking/types/capture_context.rs
src/networking/types/my_link_type.rs

Support [`Linux SLL`](https://wiki.wireshark.org/SLL) link type.
This finally makes it possible for Linux users to monitor the `any` interface, which is a pseudo device allowing to capture data on all the available interfaces.
This PR partially addresses #422.
***
In the initial implementation I tried to use `etherparse`'s [`LaxPacketHeaders::from_linux_sll`](https://docs.rs/etherparse/latest/etherparse/struct.LaxPacketHeaders.html#method.from_linux_sll) method, but it has some limitations:
- only supports `Linux SLL` version 1
- doesn't work with `NULL` / `LOOPBACK` traffic
So in the end I decided to manually extract the `protocol type` field from the header to overcome such limitations.

Support `Linux SLL` link type

---

CHANGELOG.md
src/networking/parse_packets.rs
src/networking/types/capture_context.rs

Explicitly set a timeout for the packet capture using an `mpsc` channel.
We already set a timeout on the PCAP handle, but it is ignored under Linux when there are no packets in the buffer.
Fixes #951.

Explicitly set a timeout for the packet capture using a channel

---

resources/packaging/linux/AppImage/sniffnet.yml

https://github.com/GyulyVGC/sniffnet/pull/859#issuecomment-3303347936 Seems to have been caused by Debian 13 changing the name of the libpcap package. I've updated the manifest to use the new name.

Fix AppImage error with `libpcap`

---

resources/packaging/macos/wrapper.sh

Fixes the macOS wrapper script to use relative paths instead of absolute paths, allowing the Sniffnet app to run from any location without requiring installation in the Applications folder.
1. Modified wrapper.sh to dynamically detect script directory using $(cd "$(dirname "$0")" && pwd)
2. Changed from hardcoded /*/Sniffnet.app/Contents/MacOS/sniffnet to relative path resolution
3. Used realpath to properly expand the path before passing to osascript to avoid variable expansion issues
1. Verified path resolution works correctly from different directories
2. Confirmed osascript command formation is valid
3. Tested that the script no longer depends on specific installation location
Fixes: #898

fix wrapper script to use relative path on macos
